# Generated by Django 5.0.6 on 2024-06-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_latestblogpost_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
