# Generated by Django 5.0.6 on 2025-01-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestblogpost',
            options={'verbose_name_plural': 'LatestBlogPost'},
        ),
        migrations.AlterModelOptions(
            name='owners',
            options={'verbose_name_plural': 'Owners'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
    ]
