# Generated by Django 5.0.6 on 2025-01-18 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_latestblogpost_options_alter_owners_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/owners'),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d')),
                ('image_alt', models.CharField(default='Image', max_length=255)),
                ('topic', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.owners')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.DeleteModel(
            name='LatestBlogPost',
        ),
    ]
