# Generated by Django 5.0.6 on 2025-01-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_owners_image_posts_delete_latestblogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/post/%Y/%m/%d/'),
        ),
    ]
