# Generated by Django 5.0.6 on 2025-01-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_posts_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='photo',
        ),
    ]
