# Generated by Django 5.0.6 on 2025-01-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_rename_image_posts_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='photo',
            new_name='image',
        ),
    ]
